language: cpp
compiler: gcc
sudo: require
dist: trusty

install:
 - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
 - sudo apt-get update -qq
 - sudo apt-get install  qt55base qt55declarative libsqlite3-dev qt55webkit-examples 
 - source /opt/qt*/bin/qt*-env.sh

script:
  - qmake PREFIX=/usr cuterest.pro
  - make -j4
  - find . # It did not install to /usr - let's see what's going on
  - mkdir -p appdir/usr/bin ; cd appdir
  - cp ../src/CuteRest usr/bin
  - cp ../src/cuterest.desktop .
  - cp ../src/icons/logo_256.png cuterest.png
  - cd .. 
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/* -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/* -appimage 
  - curl --upload-file ./CuteRest*.AppImage https://transfer.sh/CuteRest-git.$(git rev-parse --short HEAD)-x86_64.AppImage
